export const MUSIC_PLAY = 'MUSIC_PLAY'
export const MUSIC_PAUSE = 'MUSIC_PAUSE'
export const MUSIC_VOLUME_CHANGING_UP = 'MUSIC_VOLUME_CHANGING_UP'
export const MUSIC_VOLUME_CHANGING_DOWN = 'MUSIC_VOLUME_CHANGING_DOWN'